"""specharness-core: the domain of specharness.

Pure Python, no I/O, no framework imports (ADR-001).
"""

from .assessment import (
    DEFAULT_THRESHOLD,
    Evaluation,
    Override,
    ReadinessAssessment,
    ReadinessIssue,
    content_hash,
)
from .gherkin import Feature, Scenario, Step, parse_feature
from .linking import Link, LinkingResult, SpecInfo, link_commits
from .metrics import (
    HygieneSignal,
    MetricValue,
    ScenarioRunEvent,
    SpecMetrics,
    SprintSnapshot,
    StatusTransition,
    cycle_time_seconds,
    first_run_pass_rate,
    hygiene_report,
    is_individual_query,
    iterations_to_green,
    paired_view,
    spec_metric_values,
    tampering_signals,
    turnover_ratio,
)
from .onboarding import (
    CATEGORIES,
    OPTIONS,
    InvalidSelection,
    Selections,
    env_vars_for,
    render_config,
)
from .perception import (
    PerceptionError,
    PerceptionSample,
    SprintPerception,
    aggregate_perception,
    measured_direction,
    perceived_direction,
    perception_gap,
    validate_answers,
)
from .readiness import (
    AMBIGUOUS_TERMS,
    CoverageRow,
    Finding,
    ReadinessReport,
    evaluate_readiness,
)
from .report import (
    ReportRow,
    SprintReport,
    build_report,
    extract_numbers,
    is_faithful,
    narrative_divergences,
    render_markdown,
    report_lines,
)
from .scaffold import (
    AGENT_LAYER_FILE,
    FIXED_SPINE,
    ScaffoldParams,
    render_commit_msg_hook,
    scaffold_files,
)
from .specschema import (
    ParsedSpec,
    SpecFrontmatter,
    SpecParseError,
    SpecStatus,
    SpecType,
    can_transition,
    parse_spec,
)
from .trailers import extract_spec_trailers, valid_spec_trailers
from .verify import (
    ScenarioRun,
    VerifyReport,
    allows_done,
    done_edit_allowed,
    is_ci,
)

__all__ = [
    "DEFAULT_THRESHOLD",
    "Evaluation",
    "Override",
    "ReadinessAssessment",
    "ReadinessIssue",
    "content_hash",
    "AMBIGUOUS_TERMS",
    "CoverageRow",
    "Feature",
    "Finding",
    "HygieneSignal",
    "MetricValue",
    "PerceptionError",
    "PerceptionSample",
    "ReadinessReport",
    "ReportRow",
    "Scenario",
    "ScenarioRun",
    "ScenarioRunEvent",
    "SpecMetrics",
    "SprintPerception",
    "SprintReport",
    "SprintSnapshot",
    "StatusTransition",
    "Step",
    "VerifyReport",
    "aggregate_perception",
    "allows_done",
    "build_report",
    "cycle_time_seconds",
    "done_edit_allowed",
    "evaluate_readiness",
    "extract_numbers",
    "first_run_pass_rate",
    "hygiene_report",
    "is_ci",
    "is_faithful",
    "is_individual_query",
    "iterations_to_green",
    "measured_direction",
    "narrative_divergences",
    "paired_view",
    "parse_feature",
    "perceived_direction",
    "perception_gap",
    "render_markdown",
    "report_lines",
    "spec_metric_values",
    "tampering_signals",
    "turnover_ratio",
    "validate_answers",
    "Link",
    "LinkingResult",
    "SpecInfo",
    "link_commits",
    "ParsedSpec",
    "SpecFrontmatter",
    "SpecParseError",
    "SpecStatus",
    "SpecType",
    "can_transition",
    "parse_spec",
    "extract_spec_trailers",
    "valid_spec_trailers",
    "CATEGORIES",
    "OPTIONS",
    "InvalidSelection",
    "Selections",
    "env_vars_for",
    "render_config",
    "AGENT_LAYER_FILE",
    "FIXED_SPINE",
    "ScaffoldParams",
    "render_commit_msg_hook",
    "scaffold_files",
]

__version__ = "0.1.0"
